Fix build when LOG_DEBUG is defined
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I./src -I./src/dvdnav -I/usr/local/include -D_THREAD_SAFE -I/usr/local/include -I/usr/local/include -D_THREAD_SAFE -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -std=c99 -mno-ms-bitfields -Wall -Wsign-compare -Wextra -MT src/dvdnav.lo -MD -MP -MF src/.deps/dvdnav.Tpo -c src/dvdnav.c  -fPIC -DPIC -o src/.libs/dvdnav.o
src/dvdnav.c:559:8: error: use of undeclared identifier 'vm'
  Log3(vm, "POS-NEXT ");
       ^
src/dvdnav.c:559:8: error: use of undeclared identifier 'vm'
src/dvdnav.c:560:3: warning: implicit declaration of function 'vm_position_print' is invalid in C99 [-Wimplicit-function-declaration]